/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gui;

import finanzasapp.Form;
import finanzasapp.modelos.Ingreso;
import java.awt.Color;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class Ingresos extends javax.swing.JPanel {

    Ingreso ingreso;
    
    public Ingresos() {
        initComponents();
        llenaMeses(mesComboBox);
        llenarAnios(yearComboBox);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaIngresos = new javax.swing.JTable();
        yearComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mesComboBox = new javax.swing.JComboBox<>();
        btnEliminarIngreso = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnEditarIngreso = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        errorTxt = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaIngresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Monto", "Descripción", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaIngresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaIngresosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaIngresos);
        if (tablaIngresos.getColumnModel().getColumnCount() > 0) {
            tablaIngresos.getColumnModel().getColumn(0).setResizable(false);
            tablaIngresos.getColumnModel().getColumn(0).setPreferredWidth(80);
            tablaIngresos.getColumnModel().getColumn(1).setResizable(false);
            tablaIngresos.getColumnModel().getColumn(1).setPreferredWidth(200);
            tablaIngresos.getColumnModel().getColumn(2).setResizable(false);
            tablaIngresos.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 410, 420));

        yearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearComboBoxActionPerformed(evt);
            }
        });
        add(yearComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Lucida Sans", 2, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Buscar por...");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Año");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Mes");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, -1));

        mesComboBox.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        mesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesComboBoxActionPerformed(evt);
            }
        });
        add(mesComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        btnEliminarIngreso.setBackground(new java.awt.Color(102, 204, 255));
        btnEliminarIngreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarIngresoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarIngresoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarIngresoMouseExited(evt);
            }
        });
        btnEliminarIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Eliminar");
        btnEliminarIngreso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 60, 50));

        add(btnEliminarIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 140, 50));

        btnEditarIngreso.setBackground(new java.awt.Color(102, 204, 255));
        btnEditarIngreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarIngresoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarIngresoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarIngresoMouseExited(evt);
            }
        });
        btnEditarIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Editar");
        btnEditarIngreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        add(btnEditarIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 140, 50));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Registro de ingresos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        errorTxt.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        errorTxt.setToolTipText("");
        errorTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(errorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 260, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarIngresoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarIngresoMouseEntered
        btnEliminarIngreso.setBackground(new Color(0, 204, 255));
    }//GEN-LAST:event_btnEliminarIngresoMouseEntered

    private void btnEliminarIngresoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarIngresoMouseExited
        btnEliminarIngreso.setBackground(new Color(102, 204, 255));
    }//GEN-LAST:event_btnEliminarIngresoMouseExited

    private void btnEditarIngresoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarIngresoMouseEntered
        btnEditarIngreso.setBackground(new Color(0, 204, 255));
    }//GEN-LAST:event_btnEditarIngresoMouseEntered

    private void btnEditarIngresoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarIngresoMouseExited
        btnEditarIngreso.setBackground(new Color(102, 204, 255));
    }//GEN-LAST:event_btnEditarIngresoMouseExited

    private void yearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearComboBoxActionPerformed
        colocarDatos();
    }//GEN-LAST:event_yearComboBoxActionPerformed

    private void mesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesComboBoxActionPerformed
        colocarDatos();
    }//GEN-LAST:event_mesComboBoxActionPerformed

    private void tablaIngresosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaIngresosMouseClicked
        int row = tablaIngresos.getSelectedRow();
        double monto = (double) tablaIngresos.getValueAt(row, 0);
        String descripcion = (String) tablaIngresos.getValueAt(row, 1);
        String fecha = (String) tablaIngresos.getValueAt(row, 2);
        String[] partesFecha = fecha.split("-");
        String dia = partesFecha[0];
        String mes = partesFecha[1];
        String anio = partesFecha[2];
        
        ingreso = new Ingreso(1, dia, mes, anio, descripcion, monto);
    }//GEN-LAST:event_tablaIngresosMouseClicked

    private void btnEliminarIngresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarIngresoMouseClicked
        if(ingreso != null){
            ingreso.eliminarIngreso();
            errorTxt.setText("Ingreso eliminado");
            errorTxt.setForeground(Color.green);
            colocarDatos();
        } else {
            errorTxt.setText("Escoja una celda para eliminar.");
            errorTxt.setForeground(Color.red);
        }
    }//GEN-LAST:event_btnEliminarIngresoMouseClicked

    private void btnEditarIngresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarIngresoMouseClicked
           if(ingreso != null){
            Form.mostrarFormulario("Editar ingreso", "INGRESO", ingreso.monto, ingreso.descripcion, ingreso.dia, ingreso.mes, ingreso.anio);
            errorTxt.setText("Ingreso editado");
            errorTxt.setForeground(Color.green);
            colocarDatos();
        } else {
            errorTxt.setText("Escoja una celda para editar.");
            errorTxt.setForeground(Color.red);
        }
    }//GEN-LAST:event_btnEditarIngresoMouseClicked

    private void llenaMeses(JComboBox box){
        Date fechaActual = new Date();
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", 
            "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
        for (String mese : meses) {
            box.addItem(mese);
        }
        box.setSelectedIndex(fechaActual.getMonth());
    }
    
    private void llenarAnios(JComboBox box){
        Date fechaActual = new Date();
        int anioActual = fechaActual.getYear() + 1900;
        Integer[] years = new Integer[(anioActual - 2000) + 1];
        int currentYear = anioActual;
        for (int i = 0; i < years.length; i++) {
            years[i] = currentYear - i;
            box.addItem(Integer.toString(years[i]));
        }
    }
    
    public void colocarDatos(){
        
       DefaultTableModel modelo = (DefaultTableModel) tablaIngresos.getModel();
        modelo.setRowCount(0);
        Object[][] movimientos = Ingreso.verIngresos(obtenerMes(), obtenerAnio());
    
        for(Object[] mov:movimientos){  
            Double monto = (Double) mov[0];     
            String descripcion = (String) mov[1]; 
            String fecha = (String) mov[2];      
            Object[] nuevaFila = {monto, descripcion, fecha};
            modelo.addRow(nuevaFila);
        }
        tablaIngresos.revalidate();
        tablaIngresos.repaint();
    }
    
    public String obtenerMes(){
        String mes = (String) mesComboBox.getSelectedItem();
        
        return mes;
    }
    public String obtenerAnio(){
        String anio = (String) yearComboBox.getSelectedItem();
        
        return anio;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnEditarIngreso;
    private javax.swing.JPanel btnEliminarIngreso;
    private javax.swing.JLabel errorTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> mesComboBox;
    private javax.swing.JTable tablaIngresos;
    private javax.swing.JComboBox<String> yearComboBox;
    // End of variables declaration//GEN-END:variables
}
