/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gui;

import finanzasapp.modelos.Cuenta;
import finanzasapp.modelos.Gasto;
import finanzasapp.modelos.Ingreso;
import java.awt.Color;
import java.util.Arrays;
import java.util.Date;
import java.util.Properties;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author PC
 */
public class Movimientos extends javax.swing.JPanel {

    /**
     * Creates new form Movimientos
     */
    public Movimientos() {
        initComponents();
        llenarAnios(yearComboBox);
        llenarAnios(escogeAnio);
        llenaDias(escogeDia);
        llenaMeses(mesComboBox);
        llenaMeses(escogeMes);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMovimientos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mesComboBox = new javax.swing.JComboBox<>();
        yearComboBox = new javax.swing.JComboBox<>();
        registrarMovimiento = new javax.swing.JPanel();
        tipoMovimiento = new javax.swing.JComboBox<>();
        montoMovimiento = new javax.swing.JTextField();
        descMovimiento = new javax.swing.JTextField();
        escogeDia = new javax.swing.JComboBox<>();
        escogeMes = new javax.swing.JComboBox<>();
        escogeAnio = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        errorTxt = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(300, 300));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaMovimientos.setAutoCreateRowSorter(true);
        tablaMovimientos.setBackground(new java.awt.Color(255, 255, 255));
        tablaMovimientos.setFont(new java.awt.Font("Lucida Sans", 0, 10)); // NOI18N
        tablaMovimientos.setForeground(new java.awt.Color(0, 0, 0));
        tablaMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Monto", "Descripción", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMovimientos.setEnabled(false);
        tablaMovimientos.setFocusable(false);
        tablaMovimientos.setGridColor(new java.awt.Color(204, 204, 204));
        tablaMovimientos.setRowSelectionAllowed(false);
        tablaMovimientos.setShowGrid(true);
        jScrollPane1.setViewportView(tablaMovimientos);
        if (tablaMovimientos.getColumnModel().getColumnCount() > 0) {
            tablaMovimientos.getColumnModel().getColumn(0).setResizable(false);
            tablaMovimientos.getColumnModel().getColumn(0).setPreferredWidth(60);
            tablaMovimientos.getColumnModel().getColumn(1).setResizable(false);
            tablaMovimientos.getColumnModel().getColumn(1).setPreferredWidth(60);
            tablaMovimientos.getColumnModel().getColumn(2).setResizable(false);
            tablaMovimientos.getColumnModel().getColumn(2).setPreferredWidth(180);
            tablaMovimientos.getColumnModel().getColumn(3).setResizable(false);
            tablaMovimientos.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 340));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Registrar movimiento");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Mes");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Año");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        mesComboBox.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        mesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesComboBoxActionPerformed(evt);
            }
        });
        add(mesComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, -1, -1));

        yearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearComboBoxActionPerformed(evt);
            }
        });
        add(yearComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        registrarMovimiento.setBackground(new java.awt.Color(102, 204, 255));
        registrarMovimiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tipoMovimiento.setBackground(new java.awt.Color(255, 255, 255));
        tipoMovimiento.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        tipoMovimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INGRESO", "GASTO" }));
        registrarMovimiento.add(tipoMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 90, 30));
        registrarMovimiento.add(montoMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 100, 30));
        registrarMovimiento.add(descMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 230, 30));

        escogeDia.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        registrarMovimiento.add(escogeDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 30));

        escogeMes.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        registrarMovimiento.add(escogeMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, 30));

        escogeAnio.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        registrarMovimiento.add(escogeAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Descripción");
        registrarMovimiento.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Año");
        registrarMovimiento.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Monto");
        registrarMovimiento.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo");
        registrarMovimiento.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Día");
        registrarMovimiento.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mes");
        registrarMovimiento.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        add(registrarMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 310, 340));

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Todos los movimientos");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Lucida Sans", 2, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Buscar por...");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        btnAgregar.setBackground(new java.awt.Color(102, 204, 255));
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMouseExited(evt);
            }
        });
        btnAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Agregar");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 60, 50));

        add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 140, 50));

        errorTxt.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        errorTxt.setForeground(new java.awt.Color(255, 0, 0));
        errorTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(errorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 220, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseEntered
        btnAgregar.setBackground(new Color(0, 204, 255));
    }//GEN-LAST:event_btnAgregarMouseEntered

    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseExited
        btnAgregar.setBackground(new Color(102, 204, 255));
    }//GEN-LAST:event_btnAgregarMouseExited

    
    
    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        errorTxt.setText("");
        try{
        String tipoDeMvm = (String) tipoMovimiento.getSelectedItem();
        String montoText = montoMovimiento.getText();
        String descMvm = descMovimiento.getText();
        String dia = (String) escogeDia.getSelectedItem();
        String mes = (String) escogeMes.getSelectedItem();
        String anio = (String) escogeAnio.getSelectedItem();
        
            if (descMvm.equals("") || montoText.equals("")){
                throw new ErrorPersonalizado("Los campos no pueden estar vacios");
            }
       
        double montoMvm = Double.parseDouble(montoText); 
        if(tipoDeMvm.equals("INGRESO")){
            Ingreso.guardarIngreso(dia, mes, anio, descMvm, montoMvm);
            montoMovimiento.setText("");
            descMovimiento.setText("");
            errorTxt.setForeground(Color.GREEN);
            errorTxt.setText("Nuevo ingreso registrado");
            colocarDatos();
        } else {
            montoMovimiento.setText("");
            descMovimiento.setText("");
            Gasto.guardarGasto(dia, mes, anio, descMvm, montoMvm);
            errorTxt.setForeground(Color.GREEN);
            errorTxt.setText("Nuevo gasto registrado");
            colocarDatos();
        }
        
        } catch(NumberFormatException e){
            errorTxt.setForeground(Color.RED);
            errorTxt.setText("El monto debe ser un número");
        } catch (ErrorPersonalizado e) {
            errorTxt.setForeground(Color.RED);
            errorTxt.setText("Los campos son requeridos");
        }
        
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void yearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearComboBoxActionPerformed

        colocarDatos();
    }//GEN-LAST:event_yearComboBoxActionPerformed

    private void mesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesComboBoxActionPerformed
       colocarDatos();
    }//GEN-LAST:event_mesComboBoxActionPerformed

    public class ErrorPersonalizado extends Exception {
        public ErrorPersonalizado(String mensaje) {
            super(mensaje);
            }
    }
    
    public String obtenerMes(){
        String mes = (String) mesComboBox.getSelectedItem();
        
        return mes;
    }
    public String obtenerAnio(){
        String anio = (String) yearComboBox.getSelectedItem();
        
        return anio;
    }
    
    public void colocarDatos(){
        
       DefaultTableModel modelo = (DefaultTableModel) tablaMovimientos.getModel();
        modelo.setRowCount(0);
        Object[][] movimientos = Cuenta.mostrarTodosMovimientos(obtenerMes(), obtenerAnio());
    
        for(Object[] mov:movimientos){
            String tipo = (String) mov[0];      
            Double monto = (Double) mov[1];     
            String descripcion = (String) mov[2]; 
            String fecha = (String) mov[3];      
            Object[] nuevaFila = {tipo, monto, descripcion, fecha};
            modelo.addRow(nuevaFila);
        }
        tablaMovimientos.revalidate();
        tablaMovimientos.repaint();
    }
    
    private void llenaDias(JComboBox box){
        Date fechaActual = new Date();
        for (int i = 1; i <= 31; i++){
            box.addItem(Integer.toString(i));
        }
        box.setSelectedIndex(fechaActual.getDay() - 2);
    }
    
    private void llenaMeses(JComboBox box){
        Date fechaActual = new Date();
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", 
            "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
        for (String mese : meses) {
            box.addItem(mese);
        }
        box.setSelectedIndex(fechaActual.getMonth());
    }
    
    private void llenarAnios(JComboBox box){
        Date fechaActual = new Date();
        int anioActual = fechaActual.getYear() + 1900;
        Integer[] years = new Integer[(anioActual - 2000) + 1];
        int currentYear = anioActual;
        for (int i = 0; i < years.length; i++) {
            years[i] = currentYear - i;
            box.addItem(Integer.toString(years[i]));
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAgregar;
    private javax.swing.JTextField descMovimiento;
    private javax.swing.JLabel errorTxt;
    private javax.swing.JComboBox<String> escogeAnio;
    private javax.swing.JComboBox<String> escogeDia;
    private javax.swing.JComboBox<String> escogeMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> mesComboBox;
    private javax.swing.JTextField montoMovimiento;
    private javax.swing.JPanel registrarMovimiento;
    private javax.swing.JTable tablaMovimientos;
    private javax.swing.JComboBox<String> tipoMovimiento;
    private javax.swing.JComboBox<String> yearComboBox;
    // End of variables declaration//GEN-END:variables
}
